development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

  development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

  development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000